### PR TITLE
prettier + updated responses

### PR DESCRIPTION
**Pull request by wdhdev**

### CODE REVIEW

**Comment by wdhdev** [comment]
@andrewstech

**Comment by andrewstech** [comment]
Hello I will review this just been busy

**Comment by wdhdev** [comment]
> Hello I will review this just been busy

Ok

**Comment by andrewstech** [comment]
Um so something is broken in this **PR**

**_ERROR LOG_**
`SyntaxError: Unexpected end of input
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1048:15)
    at Module._compile (node:internal/modules/cjs/loader:1083:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\andre\is-a-dev-cli\index.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)

Node.js v18.9.0`

**Comment by wdhdev** [comment]
> Um so something is broken in this **PR**
> 
> **_ERROR LOG_** `SyntaxError: Unexpected end of input at Object.compileFunction (node:vm:360:18) at wrapSafe (node:internal/modules/cjs/loader:1048:15) at Module._compile (node:internal/modules/cjs/loader:1083:27) at Module._extensions..js (node:internal/modules/cjs/loader:1173:10) at Module.load (node:internal/modules/cjs/loader:997:32) at Module._load (node:internal/modules/cjs/loader:838:12) at Module.require (node:internal/modules/cjs/loader:1021:19) at require (node:internal/modules/cjs/helpers:103:18) at Object. (C:\Users\andre\is-a-dev-cli\index.js:7:16) at Module._compile (node:internal/modules/cjs/loader:1119:14)
> 
> Node.js v18.9.0`

Line 7 in index.js

**Pull request closed without merging**
